# Comments

In [ ]:
# Header

# Header1 

## Header2 

### Header3 

#  Python Libraries

In [3]:
import pandas as pd

In [2]:
data = {'Age':[20,45,65,23],'Name':['Bill','Sam','Dan','Mark'],'Salary':[25000,35000,20000,15000,]}

In [5]:
print(data)

{'Age': [20, 45, 65, 23], 'Name': ['Bill', 'Sam', 'Dan', 'Mark'], 'Salary': [25000, 35000, 20000, 15000]}


In [4]:
type(data)

dict

In [6]:
data1 = pd.DataFrame(data)

In [7]:
type(data1)

pandas.core.frame.DataFrame

In [ ]:
print(data1.values)

In [8]:
print(data1)

   Age  Name  Salary
0   20  Bill   25000
1   45   Sam   35000
2   65   Dan   20000
3   23  Mark   15000


In [11]:
print(data1.columns)

Index(['Age', 'Name', 'Salary'], dtype='object')


In [12]:
data1.drop('Age',axis=1)

Name  Salary
0  Bill   25000
1   Sam   35000
2   Dan   20000
3  Mark   15000

In [ ]:
print(data)

In [ ]:
print(data.drop('Age',inplace=True))

In [ ]:
print(data)

In [14]:
data1.dropna(axis=1)

Age  Name  Salary
0   20  Bill   25000
1   45   Sam   35000
2   65   Dan   20000
3   23  Mark   15000

In [ ]:
# Reading files

In [19]:
data2=pd.read_csv('diabetes.csv')
data2.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data2.describe()['Pregnancies']

In [ ]:
data3 = data2[['Pregnancies','Glucose','BloodPressure']]
data3.head()

In [ ]:
data2.isnull().sum()

In [ ]:
data2['Glucose'].mean()

In [ ]:
data2['Glucose'].fillna(120.72,inplace=True)

In [ ]:
data2.loc[:,'BloodPressure']

In [ ]:
data2.describe()

In [15]:
# Indexing and Selection

In [ ]:
print(data2['Pregnancies'])

In [ ]:
data2.columns

In [ ]:
data2.loc[10:20,['Glucose']]

In [ ]:
# loc gets rows (or columns) with particular labels from the index. 
# iloc gets rows (or columns) at particular positions in the index (so it only takes integers)

In [ ]:
print(data.loc[:,['Name']])

In [ ]:
print(data.loc[:,['Name']])

In [ ]:
data['Name'][1:3]

In [ ]:
print(data.loc[1:2,:])

In [ ]:
data2.shape

In [ ]:
print(data2.iloc[[0,1,2],[0,1]])

In [17]:
data= pd.DataFrame(data)
data.loc[data.Salary>20000]

Age  Name  Salary
0   20  Bill   25000
1   45   Sam   35000

In [20]:
print(data2.loc[data2.BMI>40])

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
4              0      137             40             35      168  43.1   
16             0      118             84             47      230  45.8   
18             1      103             30             38       83  43.3   
41             7      133             84              0        0  40.2   
43             9      171            110             24      240  45.4   
45             0      180             66             39        0  42.0   
57             0      100             88             60      110  46.8   
58             0      146             82              0        0  40.5   
59             0      105             64             41      142  41.5   
67             2      109             92              0        0  42.7   
72            13      126             90              0        0  43.4   
78             0      131              0              0        0  43.2   
84             5      137            1

In [ ]:
pd.options.display.max_categories=999
pd.options.display.max_columns=999
pd.options.display.max_info_rows=999
pd.options.display.max_rows=999
print(data2.loc[data2.BMI>40])

In [ ]:
# Filtering data using Pandas

In [ ]:
data2.head()

In [ ]:
data2['BloodPressure']>70

In [ ]:
data2[data2['BloodPressure']>90]

In [ ]:
data2[(data2['BloodPressure']>90) & (data2['Outcome']==1)]

In [ ]:
# Descriptive Statistics

In [ ]:
data2.info()

In [ ]:
data.loc[:,'Name'].mode()

In [ ]:
data.isnull().sum()

In [ ]:
print(data.loc[:,'Salary'].std())

In [ ]:
# Writing file to csv

In [ ]:
pd.DataFrame(data).to_csv('Newfile.csv')

In [ ]:
# Handling Missing Data

In [23]:
import numpy as np

import pandas as pd
data= pd.DataFrame([[2,3,np.nan],
                   [4,np.nan,4],[np.nan,3,4],
                   [4,5,6],[np.nan,np.nan,np.nan]],columns=['First','Second','Third'])

print(data)

   First  Second  Third
0    2.0     3.0    NaN
1    4.0     NaN    4.0
2    NaN     3.0    4.0
3    4.0     5.0    6.0
4    NaN     NaN    NaN


In [24]:
data.isnull().sum()

First     2
Second    2
Third     2
dtype: int64

In [25]:
print(data)

   First  Second  Third
0    2.0     3.0    NaN
1    4.0     NaN    4.0
2    NaN     3.0    4.0
3    4.0     5.0    6.0
4    NaN     NaN    NaN


In [26]:
data.dropna(how='any')

First  Second  Third
3    4.0     5.0    6.0

In [27]:
data

First  Second  Third
0    2.0     3.0    NaN
1    4.0     NaN    4.0
2    NaN     3.0    4.0
3    4.0     5.0    6.0
4    NaN     NaN    NaN

In [ ]:
data.fillna(4,inplace=True)

In [ ]:
np.mean(data.Second)

In [ ]:
print(data)

In [ ]:
data.fillna(np.mean(data),inplace=True)

In [ ]:
print(data)

# Numpy

In [38]:
import numpy as np

In [42]:
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # Create a 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.full((3, 3), True, dtype=bool)  # Create a boolean array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   # extract items that satisfy a given condition

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [45]:
arr[arr % 2 == 1] = -1
arr # replace items that satisfy a condition with another value in numpy array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [48]:
arr = np.arange(10) # Reshape an array
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
# stack two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [51]:
# get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [52]:
# remove from one array those items that exist in another
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [53]:
# get the positions where elements of two arrays match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [54]:
# extract all numbers between a given range from a numpy array
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

#  Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot([2,3,4],[3,4,4])
plt.show()

In [ ]:
x1 = ([2,4,6,10])
x2 = ([4,6,6,8])

y1 = ([2,4,6,10])
y2 = ([2,4,8,10])

plt.plot(x1,y1,linestyle='--',c='r',label='line1')

plt.plot(x2,y2,linestyle='-',c='b',label='Line2')

plt.title('Matplotlib Plots')

plt.legend(loc='upper left')

plt.xlabel('X-Value')
plt.ylabel('Y-Value')

plt.xticks([0,2,3,4,6,8,10,12])
plt.yticks([0,2,4,6,8,10,12])

plt.show()

In [ ]:
# bar plots

In [ ]:
plt.bar([11,19,14,16,14],[0.2,0.3,0.6,0.7,0.9])
plt.xticks(np.arange(11,20))
plt.title('Bar Chart')
plt.show()

In [ ]:
# Histogram

In [ ]:
x = [21,22,23,4,5,6,77,8,9,10,31,32,33,34,35,36,37,18,49,50,100]
num_bins = 5
plt.hist(x, num_bins, facecolor='darkgreen', alpha=2)
plt.show()

In [ ]:
# Scatter plots

In [ ]:
num = np.random.rand(50)
num.mean()

In [ ]:
N = 50
x = np.random.rand(N)
y = np.random.rand(N)

plt.scatter(x, y)
plt.show()

In [ ]:
# Pie charts

In [ ]:
labels = 'Python', 'C++', 'Ruby', 'Java'
sizes = [100, 400, 215, 210]

# Plot
plt.pie(sizes, labels=labels, shadow=False, startangle=250,counterclock=False)

plt.axis('equal')
plt.show()

# RegEx

In [ ]:
import re

In [ ]:
txt = "There is rain in Spain"
x = re.search("^The", txt)

if (x):
    print('Yes we have a match')
else:
    print('No Match')

In [ ]:
txt = "There is rain in Spain"
x = re.search("Spain$", txt)

if (x):
    print('Yes we have a match')
else:
    print('No Match')

In [ ]:
# Finall Function

In [ ]:
str = "There is rain in Spain"
x = re.findall("ai", str)
print(x)                         

In [ ]:
# Finall Function

In [ ]:
str = "There is rain in Mumbai"
x = re.findall("Mumbai", str)
print(x)                         

In [ ]:
# Search() Function

In [ ]:
str = "There is rain in Spain"
x = re.search("rain", str)

print("The first white-space character is located in position:", x.start())    

In [ ]:
# To get the position of Something

In [ ]:
str = 'The Cat is on the wall'
x = re.search('Cat',str)
print(x.start())                     

In [ ]:
# Split at all occurence

In [ ]:
str = "The rain in Spain"

x = re.split("\s", str)

print(x)

In [ ]:
# Split only at first occurence

In [ ]:
str = "The rain in Spain"
x = re.split("\s", str, 2)
print(x)                               

In [ ]:
# Substitue something in the string

In [ ]:
str = "ThiseraineiseineSpain"
x = re.sub("e", " ", str)
print(x)                 

In [ ]:
# Substitute and replace the first 2 occurence

In [ ]:
str = "The rain in Spain"
x = re.sub("\s", "9", str, 2)
print(x)

In [ ]:
# Printing a string from a vector

In [ ]:
str = "The rain in Spain"
x = re.search(r"\bT\w+", str)
print(x.group())

In [ ]:
# Printing a string from a vector

In [ ]:
str = "The rain in Spain"
x = re.search(r"\bS\w+", str)
print(x.group())

# Keywords in Python

In [2]:
print(False == 0)
print(True == 1)
  
print(True + True + True)
print(True + False + False)

True
True
3
1


In [4]:
x = None
y = None
print (x == y) 
  
# showing logical operation  
print (True or False) 
  
print (False and True) 
  
print (not True)

True
True
False
False


In [6]:
if 's' in 'machinelearning': 
       print ("s is part of machinelearning") 
else : print ("s is not part of machinelearning")

s is not part of machinelearning


In [8]:
# using "in" to loop through 
for i in 'Machiinelearning': 
    print (i,end=" ") 
print("\r")

M a c h i i n e l e a r n i n g 


In [9]:
# using is to check object identity 
# string is immutable( cannot be changed once alloted) 
# hence occupy same memory location 
print (' ' is ' ') 

True


In [10]:
# using is to check object identity 
# dictionary is mutable( can be changed once alloted) 
# hence occupy different memory location 
print ({} is {}) 

False


In [16]:
a = 10
def read(): 
    print (a)

In [17]:
# changing the value of globally defined variable 
def mod1(): 
    global a  
    a = 5

In [18]:
# changing value of only local variable 
def mod2(): 
    a = 15

In [19]:
read() 
mod1() 
read() 
mod2() 
read() 

10
5
5


# Exercise

In [29]:
# https://www.machinelearningpl+us.com/python/101-pandas-exercises-python/

In [30]:
# https://www.machinelearningplus.com/python/101-numpy-exercises-python/

# Questions

In [31]:
# What Is A pandas DataFrame? How Will You Create An Empty DataFrame In pandas?

In [32]:
# What Is pandas Used For?

In [33]:
# What Are The Different Ways A DataFrame Can Be Created In pandas?

In [34]:
# What is Numpy used for 

In [35]:
# What Is A Numpy Array?

In [36]:
# What Advantages Do Numpy Arrays Offer Over (nested) Python Lists?