# Comments

In [ ]:
# Header

# Header1 

## Header2 

### Header3 

#  Python Libraries

In [1]:
import pandas as pd

In [2]:
data = {'Age':[20,45,65,23],'Name':['Bill','Sam','Dan','Mark'],'Salary':[25000,35000,20000,15000,]}

In [3]:
print(data)

{'Age': [20, 45, 65, 23], 'Name': ['Bill', 'Sam', 'Dan', 'Mark'], 'Salary': [25000, 35000, 20000, 15000]}


In [4]:
type(data)

dict

In [6]:
dataframe1 = pd.DataFrame(data)

In [7]:
print(dataframe1)

   Age  Name  Salary
0   20  Bill   25000
1   45   Sam   35000
2   65   Dan   20000
3   23  Mark   15000


In [12]:
print(dataframe1.values)

[[20 'Bill' 25000]
 [45 'Sam' 35000]
 [65 'Dan' 20000]
 [23 'Mark' 15000]]


In [10]:
print(dataframe1.columns)

Index(['Age', 'Name', 'Salary'], dtype='object')


In [15]:
dataframe1.drop('Age',axis=1,inplace=True)

In [18]:
dataframe1.isnull().sum()

Name      0
Salary    0
dtype: int64

In [16]:
print(dataframe1)

   Name  Salary
0  Bill   25000
1   Sam   35000
2   Dan   20000
3  Mark   15000


In [22]:
print(dataframe1.drop('Age',inplace=True))

ValueError: labels ['Age'] not contained in axis

In [23]:
print(data)

{'Age': [20, 45, 65, 23], 'Name': ['Bill', 'Sam', 'Dan', 'Mark'], 'Salary': [25000, 35000, 20000, 15000]}


In [24]:
dataframe1.dropna(axis=1)

Name  Salary
0  Bill   25000
1   Sam   35000
2   Dan   20000
3  Mark   15000

In [ ]:
# Reading files

In [25]:
import os
os.getcwd()

'C:\\Users\\sarav\\Downloads\\Python-Stats-Day2-master'

In [96]:
data2 = pd.read_csv(r'C:\Users\sarav\Downloads\Python-Stats-Day1-master\diabetes.csv')
data2.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0        0  33.6   
1            1     85.0             66           29.0        0  26.6   
2            8    183.0             64            0.0        0  23.3   

   DiabetesPedigreeFunction   Age  Outcome  
0                     0.627  50.0        1  
1                     0.351  31.0        0  
2                     0.672  32.0        1

In [36]:
data2['BloodPressure'].describe()

count    768.000000
mean      69.105469
std       19.355807
min        0.000000
25%       62.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: BloodPressure, dtype: float64

In [43]:
data2.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               4
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         6
Outcome                     0
dtype: int64

In [99]:
data2['Glucose'].fillna(120,inplace=True)
data2['SkinThickness'].fillna(20,inplace=True)
data2['Age'].fillna(33,inplace=True)

In [49]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null float64
BloodPressure               768 non-null int64
SkinThickness               768 non-null float64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null float64
Outcome                     768 non-null int64
dtypes: float64(5), int64(4)
memory usage: 54.1 KB


In [51]:
data2.dtypes

Pregnancies                   int64
Glucose                     float64
BloodPressure                 int64
SkinThickness               float64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                         float64
Outcome                       int64
dtype: object

In [52]:
data2.describe()['Glucose']

count    768.000000
mean     120.716146
std       31.768190
min        0.000000
25%       99.000000
50%      117.000000
75%      140.000000
max      199.000000
Name: Glucose, dtype: float64

In [ ]:
data2.info()

In [53]:
data2.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.128206       0.141282      -0.076714   
Glucose                      0.128206  1.000000       0.151437       0.059179   
BloodPressure                0.141282  0.151437       1.000000       0.205383   
SkinThickness               -0.076714  0.059179       0.205383       1.000000   
Insulin                     -0.073535  0.313892       0.088933       0.434831   
BMI                          0.017683  0.223705       0.281805       0.391518   
DiabetesPedigreeFunction    -0.033523  0.134879       0.041265       0.175400   
Age                          0.543306  0.256411       0.238471      -0.109855   
Outcome                      0.221898  0.462683       0.065068       0.069559   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.313892  0.223705                  0.134879   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.434831  0.391518                  0.175400   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.060244  0.050226                  0.027368   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.543306  0.221898  
Glucose                   0.256411  0.462683  
BloodPressure             0.238471  0.065068  
SkinThickness            -0.109855  0.069559  
Insulin                  -0.060244  0.130548  
BMI                       0.050226  0.292695  
DiabetesPedigreeFunction  0.027368  0.173844  
Age                       1.000000  0.232266  
Outcome                   0.232266  1.000000

In [55]:
data3 = data2['Pregnancies']

In [61]:
pd.options.display.max_rows=999
data3 = data2[['Pregnancies','Glucose','BloodPressure']]
data3

Pregnancies  Glucose  BloodPressure
0              6    148.0             72
1              1     85.0             66
2              8    183.0             64
3              1     89.0             66
4              0    137.0             40
5              5    116.0             74
6              3     78.0             50
7             10    115.0              0
8              2    197.0             70
9              8    125.0             96
10             4    120.0             92
11            10    120.0             74
12            10    120.0             80
13             1    120.0             60
14             5    120.0             72
15             7    120.0              0
16             0    120.0             84
17             7    120.0             74
18             1    103.0             30
19             1    115.0             70
20             3    126.0             88
21             8     99.0             84
22             7    196.0             90
23             9    119.0             80
24            11    143.0             94
25            10    125.0             70
26             7    147.0             76
27             1     97.0             66
28            13    145.0             82
29             5    117.0             92
30             5    109.0             75
31             3    158.0             76
32             3     88.0             58
33             6     92.0             92
34            10    122.0             78
35             4    103.0             60
36            11    138.0             76
37             9    102.0             76
38             2     90.0             68
39             4    111.0             72
40             3    180.0             64
41             7    133.0             84
42             7    106.0             92
43             9    171.0            110
44             7    159.0             64
45             0    180.0             66
46             1    146.0             56
47             2     71.0             70
48             7    103.0             66
49             7    105.0              0
50             1    103.0             80
51             1    101.0             50
52             5     88.0             66
53             8    176.0             90
54             7    150.0             66
55             1     73.0             50
56             7    187.0             68
57             0    100.0             88
58             0    146.0             82
59             0    105.0             64
60             2     84.0              0
61             8    133.0             72
62             5     44.0             62
63             2    141.0             58
64             7    114.0             66
65             5     99.0             74
66             0    109.0             88
67             2    109.0             92
68             1     95.0             66
69             4    146.0             85
70             2    100.0             66
71             5    139.0             64
72            13    126.0             90
73             4    129.0             86
74             1     79.0             75
75             1      0.0             48
76             7     62.0             78
77             5     95.0             72
78             0    131.0              0
79             2    112.0             66
80             3    113.0             44
81             2     74.0              0
82             7     83.0             78
83             0    101.0             65
84             5    137.0            108
85             2    110.0             74
86            13    106.0             72
87             2    100.0             68
88            15    136.0             70
89             1    107.0             68
90             1     80.0             55
91             4    123.0             80
92             7     81.0             78
93             4    134.0             72
94             2    142.0             82
95             6    144.0             72
96             2     92.0   

In [57]:
data2.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
data2['Glucose'].mean()

In [ ]:
data2['Glucose'].mean()

In [ ]:
data2['Glucose'].fillna(120.72,inplace=True)

In [ ]:
data2.to_csv()

In [75]:
data2.loc[0:6,['BloodPressure','Glucose']]

BloodPressure  Glucose
0             72    148.0
1             66     85.0
2             64    183.0
3             66     89.0
4             40    137.0
5             74    116.0
6             50     78.0

In [95]:
data2[data2['Outcome']==1]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72           35.0        0  33.6   
2              8    183.0             64            0.0        0  23.3   
4              0    137.0             40           20.0      168  43.1   
6              3     78.0             50           20.0       88  31.0   
8              2    197.0             70           45.0      543  30.5   
9              8    125.0             96            0.0        0   0.0   
11            10    120.0             74            0.0        0  38.0   
13             1    120.0             60           23.0      846  30.1   
14             5    120.0             72           19.0      175  25.8   
15             7    120.0              0            0.0        0  30.0   
16             0    120.0             84           47.0      230  45.8   
17             7    120.0             74            0.0        0  29.6   
19             1    115.0             70           30.0       96  34.6   
22             7    196.0             90            0.0        0  39.8   
23             9    119.0             80           35.0        0  29.0   
24            11    143.0             94           33.0      146  36.6   
25            10    125.0             70           26.0      115  31.1   
26             7    147.0             76            0.0        0  39.4   
31             3    158.0             76           36.0      245  31.6   
37             9    102.0             76           37.0        0  32.9   
38             2     90.0             68           42.0        0  38.2   
39             4    111.0             72           47.0      207  37.1   
43             9    171.0            110           24.0      240  45.4   
45             0    180.0             66           39.0        0  42.0   
48             7    103.0             66           32.0        0  39.1   
53             8    176.0             90           34.0      300  33.7   
56             7    187.0             68           39.0      304  37.7   
61             8    133.0             72            0.0        0  32.9   
64             7    114.0             66            0.0        0  32.8   
66             0    109.0             88           30.0        0  32.5   
70             2    100.0             66           20.0       90  32.9   
72            13    126.0             90            0.0        0  43.4   
78             0    131.0              0            0.0        0  43.2   
84             5    137.0            108            0.0        0  48.8   
88            15    136.0             70           32.0      110  37.1   
93             4    134.0             72            0.0        0  23.8   
99             1    122.0             90           51.0      220  49.7   
100            1    163.0             72            0.0        0  39.0   
109            0     95.0             85           25.0       36  37.4   
110            3    171.0             72           33.0      135  33.3   
111            8    155.0             62           26.0      495  34.0   
114            7    160.0             54           32.0      175  30.5   
115            4    146.0             92            0.0        0  31.2   
116            5    124.0             74            0.0        0  34.0   
120            0    162.0             76           56.0      100  53.2   
124            0    113.0             76            0.0        0  33.3   
125            1     88.0             30           42.0       99  55.0   
128            1    117.0             88           24.0      145  34.5   
129            0    105.0             84            0.0        0  27.9   
130            4    173.0             70           14.0      168  29.7   
131            9    122.0             56            0.0        0  33.3   
132            3    170.0             64           37.0      225  34.5   
143           10    108.0             66            0.0        0  32.4   
152      

In [72]:
data2.iloc[10:13,:]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
10            4    120.0             92            0.0        0  37.6   
11           10    120.0             74            0.0        0  38.0   
12           10    120.0             80            0.0        0  27.1   

    DiabetesPedigreeFunction   Age  Outcome  
10                     0.191  33.0        0  
11                     0.537  33.0        1  
12                     1.441  33.0        0

In [ ]:
data2.describe()

In [ ]:
# Indexing and Selection

In [ ]:
print(data2['Pregnancies'])

In [ ]:
data2.columns

In [ ]:
data2.loc[10:20,['Glucose']]

In [ ]:
# loc gets rows (or columns) with particular labels from the index. 
# iloc gets rows (or columns) at particular positions in the index (so it only takes integers)

In [ ]:
print(data.loc[:,['Name']])

In [ ]:
print(data.loc[:,['Name']])

In [ ]:
data['Name'][1:3]

In [ ]:
print(data.loc[1:2,:])

In [ ]:
data2.shape

In [ ]:
print(data2.iloc[0:4,[1,3]])

In [ ]:
data= pd.DataFrame(data)
data.loc[data.Salary>20000]

In [ ]:
print(data2.loc[data2.BMI>40])

In [ ]:
pd.options.display.max_categories=999
pd.options.display.max_columns=999
pd.options.display.max_info_rows=999
pd.options.display.max_rows=999
print(data2.loc[data2.BMI>40])

In [ ]:
# Filtering data using Pandas

In [ ]:
data2.head()

In [ ]:
data2['BloodPressure']>70

In [ ]:
data2[data2['BloodPressure']>90]

In [ ]:
data2[(data2['BloodPressure']>90) & (data2['Outcome']==1)]

In [ ]:
# Descriptive Statistics

In [ ]:
data2.info()

In [ ]:
data.loc[:,'Name'].mode()

In [ ]:
data.isnull().sum()

In [ ]:
print(data.loc[:,'Salary'].std())

In [100]:
data2.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
# Writing file to csv

In [103]:
pd.DataFrame(data2).to_csv('Newfile2.csv',index=False)

In [ ]:
# Handling Missing Data

In [104]:
import numpy as np

import pandas as pd
data= pd.DataFrame([[2,3,np.nan],
                   [4,np.nan,4],[np.nan,3,4],
                   [4,5,6],[np.nan,np.nan,np.nan]],columns=['First','Second','Third'])

print(data)

   First  Second  Third
0    2.0     3.0    NaN
1    4.0     NaN    4.0
2    NaN     3.0    4.0
3    4.0     5.0    6.0
4    NaN     NaN    NaN


In [105]:
data.isnull().sum()

First     2
Second    2
Third     2
dtype: int64

In [ ]:
print(data)

In [111]:
data = data.dropna(how='all')

In [112]:
data

First  Second  Third
0    2.0     3.0    NaN
1    4.0     NaN    4.0
2    NaN     3.0    4.0
3    4.0     5.0    6.0

In [ ]:
data.fillna(4,inplace=True)

In [114]:
data['Second'].mean()

3.6666666666666665

In [113]:
np.mean(data.Second)

3.6666666666666665

In [ ]:
print(data)

In [ ]:
data.fillna(np.mean(data),inplace=True)

In [ ]:
print(data)

# Numpy

In [115]:
import numpy as np

In [123]:
numpyarray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # Create a 1D array

In [119]:
lists = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
numpyarray.size

10

In [124]:
np.full((3, 3), True, dtype=bool)  # Create a boolean array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [125]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   # extract items that satisfy a given condition

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [126]:
arr[arr % 2 == 1] = -1
arr # replace items that satisfy a condition with another value in numpy array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [128]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [129]:
arr = np.arange(10) # Reshape an array
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
# stack two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [130]:
# get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [134]:
# remove from one array those items that exist in another
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [135]:
# get the positions where elements of two arrays match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [133]:
# extract all numbers between a given range from a numpy array
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

#  Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot([2,3,4],[3,4,4])
plt.show()

In [ ]:
x1 = ([2,4,6,10])
x2 = ([4,6,6,8])

y1 = ([2,4,6,10])
y2 = ([2,4,8,10])

plt.plot(x1,y1,linestyle='--',c='r',label='line1')

plt.plot(x2,y2,linestyle='-',c='b',label='Line2')

plt.title('Matplotlib Plots')

plt.legend(loc='upper left')

plt.xlabel('X-Value')
plt.ylabel('Y-Value')

plt.xticks([0,2,3,4,6,8,10,12])
plt.yticks([0,2,4,6,8,10,12])

plt.show()

In [ ]:
# bar plots

In [ ]:
plt.bar([11,19,14,16,14],[0.2,0.3,0.6,0.7,0.9])
plt.xticks(np.arange(11,20))
plt.title('Bar Chart')
plt.show()

In [ ]:
# Histogram

In [ ]:
x = [21,22,23,4,5,6,77,8,9,10,31,32,33,34,35,36,37,18,49,50,100]
num_bins = 5
plt.hist(x, num_bins, facecolor='darkgreen', alpha=2)
plt.show()

In [ ]:
# Scatter plots

In [ ]:
num = np.random.rand(50)
num.mean()

In [ ]:
N = 50
x = np.random.rand(N)
y = np.random.rand(N)

plt.scatter(x, y)
plt.show()

In [ ]:
# Pie charts

In [ ]:
labels = 'Python', 'C++', 'Ruby', 'Java'
sizes = [100, 400, 215, 210]

# Plot
plt.pie(sizes, labels=labels, shadow=False, startangle=250,counterclock=False)

plt.axis('equal')
plt.show()

# RegEx

In [ ]:
import re

In [ ]:
txt = "There is rain in Spain"
x = re.search("^The", txt)

if (x):
    print('Yes we have a match')
else:
    print('No Match')

In [ ]:
txt = "There is rain in Spain"
x = re.search("Spain$", txt)

if (x):
    print('Yes we have a match')
else:
    print('No Match')

In [ ]:
# Finall Function

In [ ]:
str = "There is rain in Spain"
x = re.findall("ai", str)
print(x)                         

In [ ]:
# Finall Function

In [ ]:
str = "There is rain in Mumbai"
x = re.findall("Mumbai", str)
print(x)                         

In [ ]:
# Search() Function

In [ ]:
str = "There is rain in Spain"
x = re.search("rain", str)

print("The first white-space character is located in position:", x.start())    

In [ ]:
# To get the position of Something

In [ ]:
str = 'The Cat is on the wall'
x = re.search('Cat',str)
print(x.start())                     

In [ ]:
# Split at all occurence

In [ ]:
str = "The rain in Spain"

x = re.split("\s", str)

print(x)

In [ ]:
# Split only at first occurence

In [ ]:
str = "The rain in Spain"
x = re.split("\s", str, 2)
print(x)                               

In [ ]:
# Substitue something in the string

In [ ]:
str = "ThiseraineiseineSpain"
x = re.sub("e", " ", str)
print(x)                 

In [ ]:
# Substitute and replace the first 2 occurence

In [ ]:
str = "The rain in Spain"
x = re.sub("\s", "9", str, 2)
print(x)

In [ ]:
# Printing a string from a vector

In [ ]:
str = "The rain in Spain"
x = re.search(r"\bT\w+", str)
print(x.group())

In [ ]:
# Printing a string from a vector

In [ ]:
str = "The rain in Spain"
x = re.search(r"\bS\w+", str)
print(x.group())

# Keywords in Python

In [ ]:
print(False == 0)
print(True == 1)
  
print(True + True + True)
print(True + False + False)

In [ ]:
x = None
y = None
print (x == y) 
  
# showing logical operation  
print (True or False) 
  
print (False and True) 
  
print (not True)

In [ ]:
if 's' in 'machinelearning': 
       print ("s is part of machinelearning") 
else : print ("s is not part of machinelearning")

In [ ]:
# using "in" to loop through 
for i in 'Machiinelearning': 
    print (i,end=" ") 
print("\r")

In [ ]:
# using is to check object identity 
# string is immutable( cannot be changed once alloted) 
# hence occupy same memory location 
print (' ' is ' ') 

In [ ]:
# using is to check object identity 
# dictionary is mutable( can be changed once alloted) 
# hence occupy different memory location 
print ({} is {}) 

In [ ]:
a = 10
def read(): 
    print (a)

In [ ]:
# changing the value of globally defined variable 
def mod1(): 
    global a  
    a = 5

In [ ]:
# changing value of only local variable 
def mod2(): 
    a = 15

In [ ]:
read() 
mod1() 
read() 
mod2() 
read() 

# Exercise

In [ ]:
# https://www.machinelearningpl+us.com/python/101-pandas-exercises-python/

In [ ]:
# https://www.machinelearningplus.com/python/101-numpy-exercises-python/

# Questions

In [ ]:
# What Is A pandas DataFrame? How Will You Create An Empty DataFrame In pandas?

In [ ]:
# What Is pandas Used For?

In [ ]:
# What Are The Different Ways A DataFrame Can Be Created In pandas?

In [ ]:
# What is Numpy used for 

In [ ]:
# What Is A Numpy Array?

In [ ]:
# What Advantages Do Numpy Arrays Offer Over (nested) Python Lists?